project:
  type: website

website:
  title: "Limin's Machine Learning Lab"
  site-url: https://liminma.github.io/machine-learning-lab
  page-navigation: true
  navbar:
    right:
      - icon: github
        href: https://github.com/liminma/machine-learning-lab
      - icon: linkedin
        href: https://www.linkedin.com/in/liminma2021
      - text: Archive
        href: archive.qmd
format:
  html:
    theme: cosmo
    css: styles.css
