project:
  type: website

website:
  title: "Limin's Generative AI Lab"
  site-url: https://liminma.github.io/generative-ai-lab
  description: "My experiments with LLMs and related technologies."
  page-navigation: true
  navbar:
    right:
      - icon: github
        href: https://github.com/liminma
      - icon: linkedin
        href: https://www.linkedin.com/in/liminma2021
      - icon: rss
        href: index.xml
      - text: Archive
        href: archive.qmd
format:
  html:
    theme: cosmo
    css: styles.css



